modLoader = "javafml"
loaderVersion = "*"
license = "LGPLv3"

[[mods]]
modId = "sodium_extra"

version = "${version}"
displayName = "Sodium Extra"

logoFile = "assets/sodium-extra/textures/icon.png" #optional

authors = "FlashyReese"

description = '''
Features that shouldn't be in Sodium.
'''

[[dependencies.sodium_extra]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.sodium_extra]]
modId = "sodium"
type = "required"
versionRange = "[${sodium_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.sodium_extra]]
modId = "greenlight"
type = "optional"
versionRange = "[0.1.0,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "sodium-extra.mixins.json"

[[accessTransformers]]
file="accesstransformer.cfg"

[modproperties.sodium_extra]
"sodium:config_api_user" = "me.flashyreese.mods.sodiumextra.client.config.SodiumExtraConfig"
